-- STAGING ONLY. Execute as postgres; all fixtures roll back.
begin;
set local statement_timeout = '30s';
create function pg_temp.assert_true(ok boolean, label text) returns void
language plpgsql security invoker as $$ begin
  if ok is distinct from true then raise exception 'FAIL: %', label; end if;
end $$;
create function pg_temp.assert_denied(statement text) returns void
language plpgsql security invoker as $$ begin
  begin execute statement;
  exception when insufficient_privilege then return;
  end;
  raise exception 'FAIL: unexpectedly permitted statement: %', statement;
end $$;
insert into public.customers (id,line_user_id,display_name) values ('dddddddd-0000-4000-8000-000000000010','synthetic-owner-reads','Synthetic shared customer');
insert into auth.users (id,email) values ('dddddddd-0000-4000-8000-000000000001','owner-reads-0@example.invalid');
insert into public.stylists (id,name) values ('dddddddd-0000-4000-8000-000000000001','Synthetic owner 0');
insert into public.billing_accounts (stylist_id,is_master,stripe_status,period_end) values ('dddddddd-0000-4000-8000-000000000001',false,'canceled',now()-interval '1 day');
insert into public.stylist_customers (stylist_id,customer_id) values ('dddddddd-0000-4000-8000-000000000001','dddddddd-0000-4000-8000-000000000010');
insert into public.bookings (stylist_id,customer_id,start_time,end_time,status) values ('dddddddd-0000-4000-8000-000000000001','dddddddd-0000-4000-8000-000000000010',now(),now()+interval '1 hour','confirmed');
insert into public.menus (stylist_id,name,duration,price) values ('dddddddd-0000-4000-8000-000000000001','Synthetic menu',60,1000);
insert into public.availability_settings (stylist_id,day_of_week,start_time,end_time) values ('dddddddd-0000-4000-8000-000000000001',1,'09:00','18:00');
insert into public.blocked_time_slots (stylist_id,start_time,end_time) values ('dddddddd-0000-4000-8000-000000000001',now(),now()+interval '1 hour');
insert into public.customer_memos (stylist_id,customer_id,memo) values ('dddddddd-0000-4000-8000-000000000001','dddddddd-0000-4000-8000-000000000010','Synthetic memo');
insert into auth.users (id,email) values ('dddddddd-0000-4000-8000-000000000002','owner-reads-1@example.invalid');
insert into public.stylists (id,name) values ('dddddddd-0000-4000-8000-000000000002','Synthetic owner 1');
insert into public.billing_accounts (stylist_id,is_master,stripe_status,period_end) values ('dddddddd-0000-4000-8000-000000000002',false,'canceled',now()-interval '1 day');
insert into public.stylist_customers (stylist_id,customer_id) values ('dddddddd-0000-4000-8000-000000000002','dddddddd-0000-4000-8000-000000000010');
insert into public.bookings (stylist_id,customer_id,start_time,end_time,status) values ('dddddddd-0000-4000-8000-000000000002','dddddddd-0000-4000-8000-000000000010',now(),now()+interval '1 hour','confirmed');
insert into public.menus (stylist_id,name,duration,price) values ('dddddddd-0000-4000-8000-000000000002','Synthetic menu',60,1000);
insert into public.availability_settings (stylist_id,day_of_week,start_time,end_time) values ('dddddddd-0000-4000-8000-000000000002',1,'09:00','18:00');
insert into public.blocked_time_slots (stylist_id,start_time,end_time) values ('dddddddd-0000-4000-8000-000000000002',now(),now()+interval '1 hour');
insert into public.customer_memos (stylist_id,customer_id,memo) values ('dddddddd-0000-4000-8000-000000000002','dddddddd-0000-4000-8000-000000000010','Synthetic memo');
insert into auth.users (id,email) values ('dddddddd-0000-4000-8000-000000000003','owner-reads-2@example.invalid');
insert into public.stylists (id,name) values ('dddddddd-0000-4000-8000-000000000003','Synthetic owner 2');
insert into public.billing_accounts (stylist_id,is_master,stripe_status,period_end) values ('dddddddd-0000-4000-8000-000000000003',true,'canceled',now()-interval '1 day');

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"dddddddd-0000-4000-8000-000000000001","role":"authenticated"}',true);
select set_config('request.jwt.claim.sub','dddddddd-0000-4000-8000-000000000001',true);
select pg_temp.assert_true((select count(*)=1 from public.bookings where stylist_id::text like 'dddddddd-%'),'actor 0: bookings count');
select pg_temp.assert_true(not exists(select 1 from public.bookings where stylist_id <> 'dddddddd-0000-4000-8000-000000000001'),'actor 0: bookings foreign owner denied');
select pg_temp.assert_denied($q$insert into public.bookings default values$q$);
select pg_temp.assert_denied($q$update public.bookings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.bookings$q$);
select pg_temp.assert_true((select count(*)=1 from public.menus where stylist_id::text like 'dddddddd-%'),'actor 0: menus count');
select pg_temp.assert_true(not exists(select 1 from public.menus where stylist_id <> 'dddddddd-0000-4000-8000-000000000001'),'actor 0: menus foreign owner denied');
select pg_temp.assert_denied($q$insert into public.menus default values$q$);
select pg_temp.assert_denied($q$update public.menus set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.menus$q$);
select pg_temp.assert_true((select count(*)=1 from public.availability_settings where stylist_id::text like 'dddddddd-%'),'actor 0: availability_settings count');
select pg_temp.assert_true(not exists(select 1 from public.availability_settings where stylist_id <> 'dddddddd-0000-4000-8000-000000000001'),'actor 0: availability_settings foreign owner denied');
select pg_temp.assert_denied($q$insert into public.availability_settings default values$q$);
select pg_temp.assert_denied($q$update public.availability_settings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.availability_settings$q$);
select pg_temp.assert_true((select count(*)=1 from public.blocked_time_slots where stylist_id::text like 'dddddddd-%'),'actor 0: blocked_time_slots count');
select pg_temp.assert_true(not exists(select 1 from public.blocked_time_slots where stylist_id <> 'dddddddd-0000-4000-8000-000000000001'),'actor 0: blocked_time_slots foreign owner denied');
select pg_temp.assert_denied($q$insert into public.blocked_time_slots default values$q$);
select pg_temp.assert_denied($q$update public.blocked_time_slots set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.blocked_time_slots$q$);
select pg_temp.assert_true((select count(*)=1 from public.customer_memos where stylist_id::text like 'dddddddd-%'),'actor 0: customer_memos count');
select pg_temp.assert_true(not exists(select 1 from public.customer_memos where stylist_id <> 'dddddddd-0000-4000-8000-000000000001'),'actor 0: customer_memos foreign owner denied');
select pg_temp.assert_denied($q$insert into public.customer_memos default values$q$);
select pg_temp.assert_denied($q$update public.customer_memos set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.customer_memos$q$);
reset role;

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"dddddddd-0000-4000-8000-000000000002","role":"authenticated"}',true);
select set_config('request.jwt.claim.sub','dddddddd-0000-4000-8000-000000000002',true);
select pg_temp.assert_true((select count(*)=1 from public.bookings where stylist_id::text like 'dddddddd-%'),'actor 1: bookings count');
select pg_temp.assert_true(not exists(select 1 from public.bookings where stylist_id <> 'dddddddd-0000-4000-8000-000000000002'),'actor 1: bookings foreign owner denied');
select pg_temp.assert_denied($q$insert into public.bookings default values$q$);
select pg_temp.assert_denied($q$update public.bookings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.bookings$q$);
select pg_temp.assert_true((select count(*)=1 from public.menus where stylist_id::text like 'dddddddd-%'),'actor 1: menus count');
select pg_temp.assert_true(not exists(select 1 from public.menus where stylist_id <> 'dddddddd-0000-4000-8000-000000000002'),'actor 1: menus foreign owner denied');
select pg_temp.assert_denied($q$insert into public.menus default values$q$);
select pg_temp.assert_denied($q$update public.menus set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.menus$q$);
select pg_temp.assert_true((select count(*)=1 from public.availability_settings where stylist_id::text like 'dddddddd-%'),'actor 1: availability_settings count');
select pg_temp.assert_true(not exists(select 1 from public.availability_settings where stylist_id <> 'dddddddd-0000-4000-8000-000000000002'),'actor 1: availability_settings foreign owner denied');
select pg_temp.assert_denied($q$insert into public.availability_settings default values$q$);
select pg_temp.assert_denied($q$update public.availability_settings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.availability_settings$q$);
select pg_temp.assert_true((select count(*)=1 from public.blocked_time_slots where stylist_id::text like 'dddddddd-%'),'actor 1: blocked_time_slots count');
select pg_temp.assert_true(not exists(select 1 from public.blocked_time_slots where stylist_id <> 'dddddddd-0000-4000-8000-000000000002'),'actor 1: blocked_time_slots foreign owner denied');
select pg_temp.assert_denied($q$insert into public.blocked_time_slots default values$q$);
select pg_temp.assert_denied($q$update public.blocked_time_slots set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.blocked_time_slots$q$);
select pg_temp.assert_true((select count(*)=1 from public.customer_memos where stylist_id::text like 'dddddddd-%'),'actor 1: customer_memos count');
select pg_temp.assert_true(not exists(select 1 from public.customer_memos where stylist_id <> 'dddddddd-0000-4000-8000-000000000002'),'actor 1: customer_memos foreign owner denied');
select pg_temp.assert_denied($q$insert into public.customer_memos default values$q$);
select pg_temp.assert_denied($q$update public.customer_memos set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.customer_memos$q$);
reset role;

set local role authenticated;
select set_config('request.jwt.claims','{"sub":"dddddddd-0000-4000-8000-000000000003","role":"authenticated"}',true);
select set_config('request.jwt.claim.sub','dddddddd-0000-4000-8000-000000000003',true);
select pg_temp.assert_true((select count(*)=0 from public.bookings where stylist_id::text like 'dddddddd-%'),'actor 2: bookings count');
select pg_temp.assert_true(not exists(select 1 from public.bookings where stylist_id <> 'dddddddd-0000-4000-8000-000000000003'),'actor 2: bookings foreign owner denied');
select pg_temp.assert_denied($q$insert into public.bookings default values$q$);
select pg_temp.assert_denied($q$update public.bookings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.bookings$q$);
select pg_temp.assert_true((select count(*)=0 from public.menus where stylist_id::text like 'dddddddd-%'),'actor 2: menus count');
select pg_temp.assert_true(not exists(select 1 from public.menus where stylist_id <> 'dddddddd-0000-4000-8000-000000000003'),'actor 2: menus foreign owner denied');
select pg_temp.assert_denied($q$insert into public.menus default values$q$);
select pg_temp.assert_denied($q$update public.menus set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.menus$q$);
select pg_temp.assert_true((select count(*)=0 from public.availability_settings where stylist_id::text like 'dddddddd-%'),'actor 2: availability_settings count');
select pg_temp.assert_true(not exists(select 1 from public.availability_settings where stylist_id <> 'dddddddd-0000-4000-8000-000000000003'),'actor 2: availability_settings foreign owner denied');
select pg_temp.assert_denied($q$insert into public.availability_settings default values$q$);
select pg_temp.assert_denied($q$update public.availability_settings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.availability_settings$q$);
select pg_temp.assert_true((select count(*)=0 from public.blocked_time_slots where stylist_id::text like 'dddddddd-%'),'actor 2: blocked_time_slots count');
select pg_temp.assert_true(not exists(select 1 from public.blocked_time_slots where stylist_id <> 'dddddddd-0000-4000-8000-000000000003'),'actor 2: blocked_time_slots foreign owner denied');
select pg_temp.assert_denied($q$insert into public.blocked_time_slots default values$q$);
select pg_temp.assert_denied($q$update public.blocked_time_slots set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.blocked_time_slots$q$);
select pg_temp.assert_true((select count(*)=0 from public.customer_memos where stylist_id::text like 'dddddddd-%'),'actor 2: customer_memos count');
select pg_temp.assert_true(not exists(select 1 from public.customer_memos where stylist_id <> 'dddddddd-0000-4000-8000-000000000003'),'actor 2: customer_memos foreign owner denied');
select pg_temp.assert_denied($q$insert into public.customer_memos default values$q$);
select pg_temp.assert_denied($q$update public.customer_memos set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.customer_memos$q$);
reset role;

set local role anon;
select set_config('request.jwt.claims','{"role":"anon"}',true);
select set_config('request.jwt.claim.sub','',true);
select pg_temp.assert_denied($q$select * from public.bookings$q$);
select pg_temp.assert_denied($q$insert into public.bookings default values$q$);
select pg_temp.assert_denied($q$update public.bookings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.bookings$q$);
select pg_temp.assert_denied($q$select * from public.menus$q$);
select pg_temp.assert_denied($q$insert into public.menus default values$q$);
select pg_temp.assert_denied($q$update public.menus set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.menus$q$);
select pg_temp.assert_denied($q$select * from public.availability_settings$q$);
select pg_temp.assert_denied($q$insert into public.availability_settings default values$q$);
select pg_temp.assert_denied($q$update public.availability_settings set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.availability_settings$q$);
select pg_temp.assert_denied($q$select * from public.blocked_time_slots$q$);
select pg_temp.assert_denied($q$insert into public.blocked_time_slots default values$q$);
select pg_temp.assert_denied($q$update public.blocked_time_slots set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.blocked_time_slots$q$);
select pg_temp.assert_denied($q$select * from public.customer_memos$q$);
select pg_temp.assert_denied($q$insert into public.customer_memos default values$q$);
select pg_temp.assert_denied($q$update public.customer_memos set stylist_id=stylist_id$q$);
select pg_temp.assert_denied($q$delete from public.customer_memos$q$);
reset role;
select 'PASS: five business tables owner reads after expiration, cross-owner/master isolation, all client writes denied; fixtures rolled back' as result;
rollback;
